name: Sync to Repo B

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout B
        uses: actions/checkout@v4
        with:
          repository: Celfocus-AppSec-Training/devsecops-nb30640
          token: ${{ secrets.TOKEN }}
          path: repo-b

      - name: List repo B contents
        run: ls repo-b
