name: Sync to Repo B

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone Repo
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${TOKEN}@github.com/Celfocus-Appsec-Training/devsecops-nb30640.git
          rm -rf repo-b/*
          cp -r ./* repo-b/
          cd repo-b
          git add .
          git commit -m "Atualização automática do conteúdo via workflow" || echo "Nada para commitar"
          git push origin main
