name: Sync to Repo B

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repo Azure
        run: |
            git clone https://${{ secrets.USERNAME }}:${{ secrets.AZURE_PAT }}@dev.azure.com/NB30640/RepoSyncTest/_git/RepoSyncTest .

     # - name: Remove all files except azure/
     #   run: |
     #     find . -mindepth 1 ! -name 'azure' ! -path './azure/*' -exec rm -rf {} +

     # - name: Copy azure to this repo (ignoring .git and .github)
     #   run: |
     #     rsync -av --exclude='.git' --exclude='.github' azure/ ./
     #    rm -r azure/

      #- name: Commit and push changes to repo B
        # working-directory: repo-b
      #  run: |
      #    rm -r azure/
      #    git config user.name "github-actions[bot]"
      #    git config user.email "github-actions[bot]@users.noreply.github.com"
      #    git add .
      #    if git diff --cached --quiet; then
      #      echo "No changes to commit"
      #    else
      #      git commit -m "Sync changes from repo A"
      #      git push origin main
      #    fi
      - uses: stefanzweifel/git-auto-commit-action@v6
