name: Sync to Repo B

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo A
        uses: actions/checkout@v4

      - name: Checkout repo B
        uses: actions/checkout@v4
        with:
          repository: Celfocus-AppSec-Training/devsecops-nb30640
          token: ${{ secrets.TOKEN }}
          path: repo-b

      - name: Copy repo A to repo B (without deleting files, ignoring .git)
        run: |
          rsync -av --exclude='.git' --exclude='repo-b' ./ repo-b/

      - name: Commit and push changes to repo B
        working-directory: repo-b
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync changes from repo A"
            git push origin main
          fi
